apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod # Name of the Pod
  labels:
    app: sample-app
spec:
  containers:
    - name: sample # Name of the Container inside the Pod
      image: ctf/sample-app:12345
      imagePullPolicy: Never
      ports:
        - containerPort: 9000