apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod-2
  labels:
    app: sample-app
spec:
   containers:
    - name: sample-app
      image: ctf/sample-app:latest
      envFrom:
        - configMapRef:
            name: sample-app-config-map-envs
      imagePullPolicy: Never
      ports:
        - containerPort: 9000   