apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod-1
  labels:
    app: sample-app
spec:
   containers:
    - name: sample-app
      image: ctf/sample-app:latest
      env:
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: sample-app-config-map-envs
              key: GREETING
        - name: ADDITIONAL_GREETING
          value: "This additional greeting is not from the config map"      
      imagePullPolicy: Never
      ports:
        - containerPort: 9000

   