apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod-2
  labels:
    app: sample-app
spec:
  containers:
    - name: sample-app
      image: ctf/sample-app:latest
      envFrom:
        - secretRef:
            name: sample-app-secret-1
      imagePullPolicy: Never
      ports:
        - containerPort: 9000