apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod-3
  labels:
    app: sample-app
spec:
  containers:
    - name: sample-app
      image: ctf/sample-app:latest
      volumeMounts:
        - name: config-volume
          mountPath: ./config/
      imagePullPolicy: Never
      ports:
        - containerPort: 9000
  volumes:
    - name: config-volume
      secret:
        secretName: sample-app-secret-2